/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_reinford_DirectTouch */

#ifndef _Included_net_reinford_DirectTouch
#define _Included_net_reinford_DirectTouch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_reinford_DirectTouch
 * Method:    isDefaultTouch
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_reinford_DirectTouch_isDefaultTouch
  (JNIEnv *, jobject);

/*
 * Class:     net_reinford_DirectTouch
 * Method:    onTouchEvent
 * Signature: ([I[D[I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_net_reinford_DirectTouch_onTouchEvent
  (JNIEnv *, jobject, jintArray, jdoubleArray, jintArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
